services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always # If the container crashes or your system restarts, without this If container stops → database goes down. You’d have to manually restart.
    environment: # for env variable
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

volumes:
  auth_pgdata:
